/**
 * Task 50: stable resource lineage across rename and recovery.
 *
 * Task 48's resource_symbol table already keeps a (tenant, type, source id)
 * row's current natural key up to date across a rename, but it retains only
 * the CURRENT alias and offers no way to unify a genuinely recreated object
 * (a new Graph id after permanent deletion) with its predecessor's history.
 * This module layers that on top, independently persisted:
 *
 *  - resource_lineage: one durable row per (tenant, type, source id) — the
 *    logical resource identity. Never regenerated by a rename; only a new
 *    source id starts a new lineage.
 *  - resource_lineage_alias: every natural key a lineage has ever held, each
 *    with an explicit validity window. At most one row per lineage is
 *    currently open (valid_until IS NULL).
 *  - resource_lineage_recovery: the only mechanism allowed to declare two
 *    DIFFERENT lineages (hence two different source ids) continuations of the
 *    same real-world resource. It requires explicit evidence and a tombstoned
 *    predecessor — name reuse alone is never sufficient.
 *
 * Resolving a natural key back to a lineage is deliberately conservative: a
 * live (currently-held) match resolves cleanly; anything else consults full
 * history and REFUSES when more than one distinct lineage ever held that name
 * — an ambiguous alias must never be guessed at, and a closed (expired) alias
 * is always reported `stale: true`, never silently treated as current.
 */
import { CONTEXT_EXCLUDED_TYPES } from '../cir/canonicalize.mjs';

// Mirrors resourceSymbols.mjs's normalization: Graph GUIDs are not guaranteed
// consistent letter casing across endpoints/runs, and global template
// catalogues (directoryRoleTemplate, directorySettingTemplate) are excluded
// because their ids are global constants, never tenant identity.
function sourceIdFor(resourceType, sourceId) {
  if (CONTEXT_EXCLUDED_TYPES.has(resourceType)) return null;
  return typeof sourceId === 'string' && sourceId.length > 0 ? sourceId.toLowerCase() : null;
}

/**
 * Records one observation of a (tenant, type, source id) resource under
 * `naturalKey`. Finds-or-creates the lineage row (never regenerated by a
 * rename) and, when the current open alias differs, closes it and opens a
 * fresh one at `observedAt` — an explicit validity window, not an in-place
 * rewrite. Re-observing a tombstoned lineage clears the tombstone: the
 * current batch always overrides persisted lineage state, exactly as task
 * 48's resource_symbol does.
 */
export async function recordLineage(client, { tenantRef, resourceType, sourceId, naturalKey, snapshotId = null, observedAt = new Date() }) {
  const normalizedSourceId = sourceIdFor(resourceType, sourceId);
  if (!normalizedSourceId) return null;

  const { rows: [lineage] } = await client.query(
    `INSERT INTO resource_lineage (tenant_ref, resource_type, source_id)
     VALUES ($1, $2, $3)
     ON CONFLICT (tenant_ref, resource_type, source_id) DO UPDATE
       SET tombstoned_at = NULL
     RETURNING id`,
    [tenantRef, resourceType, normalizedSourceId],
  );

  const { rows: [current] } = await client.query(
    `SELECT id, natural_key FROM resource_lineage_alias
      WHERE lineage_id = $1 AND valid_until IS NULL`,
    [lineage.id],
  );

  if (current && current.natural_key === naturalKey) {
    return { lineageId: lineage.id, renamed: false };
  }

  if (current) {
    await client.query(
      `UPDATE resource_lineage_alias SET valid_until = $2 WHERE id = $1`,
      [current.id, observedAt],
    );
  }
  await client.query(
    `INSERT INTO resource_lineage_alias (lineage_id, natural_key, valid_from, valid_until, source_snapshot)
     VALUES ($1, $2, $3, NULL, $4)`,
    [lineage.id, naturalKey, observedAt, snapshotId],
  );
  return { lineageId: lineage.id, renamed: current != null };
}

/**
 * Tombstones every live lineage of `resourceType` not present in
 * `observedSourceIds`. Callers must only invoke this for a successful FULL
 * per-type enumeration (mirrors resource_symbol's rule) — a failed or partial
 * read proves nothing about absence and must never call this.
 */
export async function tombstoneMissingLineages(client, { tenantRef, resourceType, observedSourceIds, observedAt = new Date() }) {
  const normalized = observedSourceIds
    .map((id) => sourceIdFor(resourceType, id))
    .filter(Boolean);
  const { rowCount } = await client.query(
    `UPDATE resource_lineage
        SET tombstoned_at = $3
      WHERE tenant_ref = $1 AND resource_type = $2 AND tombstoned_at IS NULL
        AND NOT (source_id = ANY($4))`,
    [tenantRef, resourceType, observedAt, normalized],
  );
  return { tombstoned: rowCount };
}

/** The live lineage (id, current alias, tombstone state) for one source id, or null. */
export async function currentLineageFor(client, { tenantRef, resourceType, sourceId }) {
  const normalized = sourceIdFor(resourceType, sourceId);
  if (!normalized) return null;
  const { rows: [row] } = await client.query(
    `SELECT rl.id AS lineage_id, rl.tombstoned_at, rla.natural_key
       FROM resource_lineage rl
       LEFT JOIN resource_lineage_alias rla ON rla.lineage_id = rl.id AND rla.valid_until IS NULL
      WHERE rl.tenant_ref = $1 AND rl.resource_type = $2 AND rl.source_id = $3`,
    [tenantRef, resourceType, normalized],
  );
  return row ?? null;
}

/**
 * The natural key that was current for `lineageId` at `asOf` — the alias row
 * whose validity window contains that instant. A historical snapshot resolves
 * the identity that was current WHEN IT WAS TAKEN, never today's latest name.
 */
export async function naturalKeyAsOf(client, { lineageId, asOf }) {
  const { rows: [row] } = await client.query(
    `SELECT natural_key FROM resource_lineage_alias
      WHERE lineage_id = $1 AND valid_from <= $2 AND (valid_until IS NULL OR valid_until > $2)
      ORDER BY valid_from DESC LIMIT 1`,
    [lineageId, asOf],
  );
  return row?.natural_key ?? null;
}

/**
 * Resolves a bare natural key back to the lineage that owns it — by name
 * alone, with no time anchor. A single CURRENT (live, non-tombstoned) holder
 * resolves cleanly (`stale: false`). Absent a live holder, every lineage that
 * has EVER held this name is considered: exactly one candidate resolves as a
 * stale historical match; more than one is genuinely ambiguous (the classic
 * "unrelated name reuse" case) and MUST refuse rather than guess.
 */
export async function resolveNaturalKey(client, { tenantRef, resourceType, naturalKey }) {
  const { rows: liveRows } = await client.query(
    `SELECT rl.id AS lineage_id
       FROM resource_lineage rl
       JOIN resource_lineage_alias rla ON rla.lineage_id = rl.id AND rla.valid_until IS NULL
      WHERE rl.tenant_ref = $1 AND rl.resource_type = $2 AND rla.natural_key = $3
        AND rl.tombstoned_at IS NULL`,
    [tenantRef, resourceType, naturalKey],
  );
  if (liveRows.length === 1) {
    return { resolved: true, lineageId: liveRows[0].lineage_id, stale: false };
  }
  if (liveRows.length > 1) {
    return { resolved: false, reason: 'ambiguous-current-alias' };
  }

  const { rows: historicalRows } = await client.query(
    `SELECT DISTINCT rla.lineage_id
       FROM resource_lineage_alias rla
       JOIN resource_lineage rl ON rl.id = rla.lineage_id
      WHERE rl.tenant_ref = $1 AND rl.resource_type = $2 AND rla.natural_key = $3`,
    [tenantRef, resourceType, naturalKey],
  );
  if (historicalRows.length === 0) return { resolved: false, reason: 'not-found' };
  if (historicalRows.length > 1) return { resolved: false, reason: 'ambiguous-alias' };
  return { resolved: true, lineageId: historicalRows[0].lineage_id, stale: true };
}

/**
 * Records an evidenced recovery link from a tombstoned predecessor lineage to
 * its successor — the only path that may treat a brand-new source id as a
 * continuation of an old one. Every guard here is mandatory, never optional:
 * non-empty evidence, distinct lineages, both rows must belong to the calling
 * tenant, and the predecessor must already be tombstoned (a live lineage has
 * not gone anywhere and cannot be "recovered from").
 */
export async function recordRecovery(client, { tenantRef, predecessorLineageId, successorLineageId, evidence, recordedBy }) {
  if (!evidence || typeof evidence !== 'object' || Array.isArray(evidence) || Object.keys(evidence).length === 0) {
    throw new Error('resource-lineage-recovery-requires-evidence');
  }
  if (predecessorLineageId === successorLineageId) {
    throw new Error('resource-lineage-recovery-requires-distinct-lineages');
  }
  const { rows: [predecessor] } = await client.query(
    `SELECT tombstoned_at FROM resource_lineage WHERE id = $1 AND tenant_ref = $2`,
    [predecessorLineageId, tenantRef],
  );
  if (!predecessor) throw new Error('resource-lineage-recovery-unknown-predecessor');
  if (!predecessor.tombstoned_at) throw new Error('resource-lineage-recovery-predecessor-not-tombstoned');
  const { rows: [successor] } = await client.query(
    `SELECT id FROM resource_lineage WHERE id = $1 AND tenant_ref = $2`,
    [successorLineageId, tenantRef],
  );
  if (!successor) throw new Error('resource-lineage-recovery-unknown-successor');

  const { rows: [row] } = await client.query(
    `INSERT INTO resource_lineage_recovery (tenant_ref, predecessor_id, successor_id, evidence, recorded_by)
     VALUES ($1, $2, $3, $4, $5)
     RETURNING id`,
    [tenantRef, predecessorLineageId, successorLineageId, JSON.stringify(evidence), recordedBy],
  );
  return { recoveryId: row.id };
}

/**
 * Walks successor -> predecessor recovery links to the earliest ancestor,
 * returning `[lineageId, ...ancestors]`. The last element is the "effective"
 * identity two recovery-linked lineages share — used by diffSnapshots.mjs to
 * treat an evidenced recreation as one continuous resource history, and never
 * populated for an ordinary rename (same lineage row already) or an
 * unrelated, unlinked name reuse (no recovery row exists at all).
 */
export async function recoveryChainFor(client, { tenantRef, lineageId }) {
  const chain = [lineageId];
  let current = lineageId;
  for (;;) {
    const { rows: [link] } = await client.query(
      `SELECT predecessor_id FROM resource_lineage_recovery WHERE tenant_ref = $1 AND successor_id = $2`,
      [tenantRef, current],
    );
    if (!link) break;
    current = link.predecessor_id;
    chain.push(current);
  }
  return chain;
}

/**
 * Loads a fallback context for engine/cir/canonicalize.mjs, shaped exactly
 * like engine/store/resourceSymbols.mjs's loadSymbolContext (Map<lowercase
 * source id, { symbol, type }>) so both can feed the same resolution
 * codepath. Unlike that context, this one is keyed by TOMBSTONED predecessor
 * source ids and resolves to their evidenced successor's CURRENT natural key
 * — the one case task 48's context structurally cannot cover, because it only
 * ever holds live (non-tombstoned) aliases.
 */
export async function loadRecoveryContext(client, { tenantRef }) {
  const { rows } = await client.query(
    `SELECT predecessor.resource_type AS type,
            predecessor.source_id AS predecessor_source_id,
            successor_alias.natural_key AS symbol
       FROM resource_lineage_recovery recovery
       JOIN resource_lineage predecessor ON predecessor.id = recovery.predecessor_id
       JOIN resource_lineage_alias successor_alias
         ON successor_alias.lineage_id = recovery.successor_id AND successor_alias.valid_until IS NULL
      WHERE recovery.tenant_ref = $1`,
    [tenantRef],
  );
  const context = new Map();
  for (const row of rows) {
    context.set(row.predecessor_source_id, { symbol: row.symbol, type: row.type });
  }
  return context;
}
