/**
 * Roadmap task-68 boundary tests: reconstruct keel read-only from independent
 * artifacts. Exercises the production tools/recovery/reconstruct.mjs workflow
 * and engine/authz/recoveryMode.mjs against the isolated test database (a
 * populated "source" tenant history dumped to gzip SQL, then reconstructed
 * into empty disposable databases) — including the three required mutation
 * checks:
 *
 * - Enable writes during reconstruction.
 * - Accept tampered manifest.
 * - Allow anonymous emergency identity.
 *
 * Plus two reviewer-derived mutations closed 2026-09-26:
 * - Remove tenant_ref filter from reconstructed schedule query (multi-tenant
 *   fixture: a second tenant's schedules ride the same dump).
 * - Remove top-level assertTenantRef guard in reconstructRecovery (invalid or
 *   undefined tenantRef).
 */
import { strict as assert } from 'node:assert';
import { generateKeyPairSync } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { appendFile, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { gzipSync } from 'node:zlib';
import { after, before, test } from 'node:test';

import {
  authenticateRecoveryIdentity,
  listMissingPrerequisites,
  openRecoveryReadOnlySession,
  PREREQUISITE_ARTIFACT_STORAGE_READ,
  PREREQUISITE_RECOVERY_KEY_MATERIAL,
  PREREQUISITE_TENANT_RECOVERY_AUTHORIZATION,
  RecoveryIdentityError,
  RecoveryReadOnlyError,
} from '../authz/recoveryMode.mjs';
import { exportSnapshot } from '../export/configExport.mjs';
import { sha256Hex } from '../export/manifest.mjs';
import { requestApproval, approveRequest, rejectRequest } from '../govern/approvals.mjs';
import { appendEvidence, verifyChain } from '../govern/evidence.mjs';
import {
  buildRecoveryManifest,
  currentSchemaPin,
  INCOMPLETE_EVIDENCE_CHECKPOINT,
} from '../storage/recoveryManifest.mjs';
import { completeSnapshot, createSnapshot, insertResourceVersion } from '../store/db.mjs';
import { seedSchedules } from '../store/scheduleSeed.mjs';
import { createIsolatedTestDatabase } from '../test/dbTestHelper.mjs';
import { fullSuccessfulCoverageDigest } from '../test/fullSuccessfulCoverage.mjs';
import {
  createDisposableTarget,
  reconstructRecovery,
  runCli,
} from '../../tools/recovery/reconstruct.mjs';
import { signRecoveryAssertion } from '../../tools/recovery/recovery-assertion.mjs';
import { decodeCopyField, parseDump } from '../../tools/recovery/dumpImport.mjs';

const source = await createIsolatedTestDatabase(`${import.meta.url}#source`);
const tmp = mkdtempSync(join(tmpdir(), 'keel-recovery-'));
// Disposable targets created during the run, cleaned up in after().
const targets = [];
let sourceClient;
let fixture;

const TENANT = 'sha256:reconstruct-fixture';
// A second tenant's schedules ride along in the same dump so the recovered
// read can be proven to be tenant-scoped, not merely absent other data
// (mutation pin: remove tenant_ref filter from reconstructed schedule query).
const OTHER_TENANT = 'sha256:reconstruct-fixture-other';
const BUILD_REVISION = 'b'.repeat(40);
let schemaPin;

const QUIET_SINK = () => {};

// The tables a reconstruction must carry, in foreign-key-safe order, with
// explicit column lists so the dump is deterministic.
const DUMP_TABLES = [
  ['principal', ['id', 'external_id', 'email', 'display_name', 'disabled_at']],
  ['role_grant', ['id', 'principal_id', 'role', 'scope', 'active_from', 'active_until', 'granted_by', 'reason']],
  ['job', ['id', 'kind', 'params', 'status', 'requested_by', 'created_at', 'started_at', 'finished_at', 'result', 'error', 'worker_id', 'heartbeat_at', 'idempotency_key', 'not_before']],
  ['approval_request', ['id', 'action', 'params', 'requested_by', 'justification', 'status', 'decided_by', 'decided_at', 'reason', 'created_at', 'expires_at']],
  ['schedule', ['id', 'tenant_ref', 'job_kind', 'tier', 'cadence', 'cron_override', 'enabled', 'next_due_at', 'last_job_id', 'created_at', 'updated_at']],
  ['evidence', ['seq', 'tenant_ref', 'occurred_at', 'kind', 'subject', 'actor', 'prev_hash', 'record_hash']],
  ['evidence_head', ['tenant_ref', 'head_seq', 'head_hash', 'record_count', 'updated_at']],
];

function sqlLiteral(value) {
  if (value === null || value === undefined) return 'NULL';
  if (value instanceof Date) return `'${value.toISOString()}'::timestamptz`;
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'number' || typeof value === 'bigint') return String(value);
  if (typeof value === 'object') return `'${JSON.stringify(value).replaceAll("'", "''")}'::jsonb`;
  return `'${String(value).replaceAll("'", "''")}'`;
}

/** Renders the source tables as an executable INSERT dump. */
async function renderDumpSql(client, { corruptEvidenceHash = false, omitTables = [] } = {}) {
  const statements = ['-- keel fixture dump generated by engine/roadmap/keel-recovery.test.mjs'];
  for (const [table, columns] of DUMP_TABLES) {
    if (omitTables.includes(table)) continue;
    const { rows } = await client.query(`SELECT ${columns.join(', ')} FROM ${table} ORDER BY 1`);
    if (rows.length === 0) continue;
    const values = rows.map((row) => `(${columns.map((column) => {
      let value = row[column];
      if (corruptEvidenceHash && table === 'evidence' && column === 'record_hash' && row.seq === rows[0].seq) {
        value = '0'.repeat(64);
      }
      return sqlLiteral(value);
    }).join(', ')})`);
    statements.push(`INSERT INTO ${table} (${columns.join(', ')}) VALUES\n${values.join(',\n')};`);
  }
  statements.push(`SELECT setval('evidence_seq_seq', (SELECT max(seq) FROM evidence));`);
  return statements.join('\n');
}

/** Populates the source tenant history: schedules, approvals, grants, evidence. */
async function buildSourceFixture() {
  sourceClient = await source.connect();
  await sourceClient.query(readFileSync(new URL('../store/schema.sql', import.meta.url), 'utf8'));

  // Grants: an operator (requester) and an approver.
  const { rows: [requester] } = await sourceClient.query(
    `INSERT INTO principal (email, display_name) VALUES ($1, $2) RETURNING *`,
    ['requester@example.test', 'Fixture Requester'],
  );
  const { rows: [approver] } = await sourceClient.query(
    `INSERT INTO principal (email, display_name) VALUES ($1, $2) RETURNING *`,
    ['approver@example.test', 'Fixture Approver'],
  );
  for (const [principal, role] of [[requester, 'operator'], [approver, 'approver']]) {
    await sourceClient.query(
      `INSERT INTO role_grant (principal_id, role, granted_by, reason) VALUES ($1, $2, $3, $4)`,
      [principal.id, role, 'fixture-admin', 'fixture grant'],
    );
  }

  // Schedules: the standard six for this tenant, plus another tenant's six
  // in the same table/dump — the reconstructed read must return only the
  // requested tenant's rows even though both are physically present.
  await seedSchedules(sourceClient, { tenantRef: TENANT });
  await seedSchedules(sourceClient, { tenantRef: OTHER_TENANT });

  // Approvals: one approved (mints a job), one rejected — both on evidence.
  const approved = await requestApproval(sourceClient, {
    tenantRef: TENANT,
    action: 'collect',
    params: { tier: 'tier1' },
    requestedBy: requester.id,
    justification: 'fixture approval to approve',
  });
  await approveRequest(sourceClient, { tenantRef: TENANT, id: approved.id, decidedBy: approver.id });
  const rejected = await requestApproval(sourceClient, {
    tenantRef: TENANT,
    action: 'collect',
    params: { tier: 'tier3' },
    requestedBy: requester.id,
    justification: 'fixture approval to reject',
  });
  await rejectRequest(sourceClient, {
    tenantRef: TENANT, id: rejected.id, decidedBy: approver.id, reason: 'fixture rejection',
  });
  await appendEvidence(sourceClient, {
    tenantRef: TENANT,
    kind: 'backup-complete',
    subject: { dump: 'fixture' },
    actor: 'fixture-operator',
    eventSink: QUIET_SINK,
  });

  // A completed snapshot + configuration export for the manifest link.
  const snapshotId = await createSnapshot(sourceClient, { tenantRef: TENANT });
  await insertResourceVersion(sourceClient, {
    snapshotId,
    resource: {
      naturalKey: 'user:ana@example.test',
      resourceType: 'user',
      payload: { id: 'u1', userPrincipalName: 'ana@example.test', displayName: 'Fixture User' },
      payloadHash: 'fixture-hash',
      criticality: 'tier1',
      blastRadius: 'access-affecting',
      fidelity: 'read-only',
      provenance: { adapter: 'fixture', collectedAt: '2026-09-22T00:00:00.000Z', fidelity: 'read-only' },
    },
  });
  await completeSnapshot(sourceClient, {
    id: snapshotId,
    status: 'complete',
    coverageDigest: { ...fullSuccessfulCoverageDigest(), user: { outcome: 'complete', itemCount: 1 } },
  });
  const { exportDir } = await exportSnapshot(sourceClient, {
    tenantRef: TENANT, snapshotId, exportRoot: join(tmp, 'export'),
  });
  const exportManifestBytes = await readFile(join(exportDir, 'manifest.json'));
  const exportManifest = JSON.parse(exportManifestBytes.toString('utf8'));

  // The dump artifact over the populated history.
  const dumpBytes = gzipSync(await renderDumpSql(sourceClient));
  const dumpPath = join(tmp, 'dump.sql.gz');
  await writeFile(dumpPath, dumpBytes);

  const { rows: [head] } = await sourceClient.query(
    'SELECT head_seq, head_hash, record_count FROM evidence_head WHERE tenant_ref = $1',
    [TENANT],
  );
  const checkpoint = {
    headSeq: Number(head.head_seq),
    headHash: head.head_hash,
    recordCount: Number(head.record_count),
  };

  const manifest = buildRecoveryManifest({
    tenantRef: TENANT,
    build: { revision: BUILD_REVISION, schemaPin },
    dump: { path: dumpPath, sha256: sha256Hex(dumpBytes), bytes: dumpBytes.length },
    observationIds: Object.keys(exportManifest.types).map((type) => `${snapshotId}:${type}`),
    configExport: {
      manifestPath: join(exportDir, 'manifest.json'),
      manifestSha256: sha256Hex(exportManifestBytes),
    },
    evidenceCheckpoint: checkpoint,
    residency: { provider: 'local-disk', region: 'on-prem datacenter A' },
    keyRecovery: {
      heldBy: 'security officer',
      location: 'offline safe, sealed envelope #7',
      instructions: 'Retrieve envelope #7 from the offline safe; the passphrase is held separately.',
    },
  });
  const manifestPath = join(tmp, 'recovery.json');
  await writeFile(manifestPath, `${JSON.stringify(manifest)}\n`);

  return {
    snapshotId, exportDir, dumpBytes, dumpPath, checkpoint, manifest, manifestPath,
    build: { revision: BUILD_REVISION, schemaPin },
    principals: { requester, approver },
  };
}

before(async () => {
  schemaPin = await currentSchemaPin();
  fixture = await buildSourceFixture();
});

after(async () => {
  await sourceClient?.end();
  await source.cleanup();
  for (const target of targets.splice(0)) await target.cleanup();
  rmSync(tmp, { recursive: true, force: true });
});

/** Creates and tracks an empty disposable database (no schema applied). */
async function newTarget() {
  const target = await createIsolatedTestDatabase(`${import.meta.url}#target-${targets.length}`);
  // reconstructRecovery discards a target whose import failed; the after hook
  // must not drop it a second time.
  const cleanup = target.cleanup;
  let cleaned;
  target.cleanup = () => (cleaned ??= cleanup.call(target));
  targets.push(target);
  return target;
}

function baseOptions(overrides = {}) {
  return {
    tenantRef: TENANT,
    manifestPath: fixture.manifestPath,
    dumpPath: fixture.dumpPath,
    configExportDir: fixture.exportDir,
    expectedBuild: fixture.build,
    expectedCheckpoint: fixture.checkpoint,
    identity: {
      principalId: 'recovery-officer@example.test',
      credentialRef: 'break-glass token reference: safe #7, held by security officer',
    },
    authenticator: async () => true,
    credentials: {
      recoveryKeyMaterial: 'sealed envelope #7, offline safe',
      artifactStorageRead: 'backup service account reference: keel-backup@service-accounts',
      tenantRecoveryAuthorization: 'change record CR-2026-0915 signed by the security officer',
    },
    createTargetDatabase: newTarget,
    ...overrides,
  };
}

/** Reads the recovered tables straight out of a database handle, for comparison. */
async function readHistory(connect, tenantRef) {
  const client = await connect();
  try {
    const out = {};
    for (const [table, columns] of DUMP_TABLES) {
      const { rows } = await client.query(`SELECT ${columns.join(', ')} FROM ${table} ORDER BY 1`);
      out[table] = rows;
    }
    out.chain = await verifyChain(client, { tenantRef });
    return out;
  } finally {
    await client.end();
  }
}

test('empty disposable instance recovers fixture history with writers disabled', async () => {
  const result = await reconstructRecovery(baseOptions());
  assert.equal(result.ok, true, JSON.stringify(result.failures));
  assert.equal(result.stage, 'recovered');
  assert.equal(result.readOnly, true);
  assert.equal(result.writersDisabled, true);
  assert.equal(result.identity.principalId, 'recovery-officer@example.test');
  assert.equal(result.identity.independent, true);
  assert.equal(result.recoveryComplete, true);
  assert.deepEqual(result.incomplete, []);

  // The named fixture history landed in the empty disposable instance.
  assert.equal(result.recovered.schedules.length, 6);
  assert.deepEqual(
    result.recovered.schedules.map((row) => `${row.job_kind}:${row.tier ?? ''}`).sort(),
    ['api-drift:', 'collect:tier1', 'collect:tier2', 'collect:tier3', 'offsite:', 'prune:'],
  );
  assert.equal(result.recovered.approvals.length, 2);
  assert.deepEqual(
    result.recovered.approvals.map((row) => row.status).sort(),
    ['approved', 'rejected'],
  );
  assert.equal(result.recovered.jobCount, 1, 'the approved request minted exactly one job');
  assert.equal(result.recovered.principals.length, 2);
  assert.equal(result.recovered.grants.length, 2);
  assert.deepEqual(
    result.recovered.grants.map((row) => row.role).sort(),
    ['approver', 'operator'],
  );
  assert.deepEqual(result.recovered.evidence, {
    chainOk: true,
    headSeq: fixture.checkpoint.headSeq,
    headHash: fixture.checkpoint.headHash,
    recordCount: fixture.checkpoint.recordCount,
  });

  // Row-for-row, the disposable instance reproduces the source history.
  const expected = await readHistory(() => source.connect(), TENANT);
  const actual = await readHistory(() => result.target.connect(), TENANT);
  assert.deepEqual(
    JSON.parse(JSON.stringify(actual)),
    JSON.parse(JSON.stringify(expected)),
    'schedules, approvals, grants, evidence and the chain head round-trip byte-equal',
  );
  assert.deepEqual(actual.chain, { ok: true });

  // Mutation pin: enable writes during reconstruction. The access session is
  // read-only at the database level — a write on the RAW connection fails
  // with SQLSTATE 25006 even if the statement guard were bypassed.
  await assert.rejects(
    result.access.client.query(`INSERT INTO evidence (tenant_ref, kind, subject, actor, record_hash)
      VALUES ('${TENANT}', 'tamper', '{}'::jsonb, 'tamper', 'x')`),
    (error) => error.code === '25006',
  );
  // The statement guard refuses writes before they reach the database —
  // including a writable CTE smuggled behind a leading WITH.
  await assert.rejects(result.access.query('DELETE FROM evidence'), RecoveryReadOnlyError);
  await assert.rejects(result.access.query('  update schedule set enabled = false'), RecoveryReadOnlyError);
  await assert.rejects(
    result.access.query('WITH d AS (DELETE FROM evidence RETURNING *) SELECT * FROM d'),
    RecoveryReadOnlyError,
  );
  // Reads still work through the guard.
  const { rows } = await result.access.query('SELECT count(*)::int AS n FROM schedule WHERE tenant_ref = $1', [TENANT]);
  assert.equal(rows[0].n, 6);

  await result.access.client.end();
});

/** COPY text-format encoding of one value, as pg_dump writes it. */
function copyField(value) {
  if (value === null) return '\\N';
  return value.replaceAll('\\', '\\\\').replaceAll('\t', '\\t').replaceAll('\n', '\\n').replaceAll('\r', '\\r');
}

/**
 * Renders the source tables the way plain pg_dump 16.10+ does: \restrict,
 * session SETs, DDL that collides with the pinned schema, a function body
 * holding ';' and a line starting with COPY, COPY blocks (here children
 * before parents) and a public.-qualified setval.
 */
async function renderPgDumpSql(client) {
  const out = [
    '--',
    '-- PostgreSQL database dump',
    '--',
    '',
    '\\restrict fixtureRestrictKey0123456789',
    '',
    "SET statement_timeout = 0;",
    "SET client_encoding = 'UTF8';",
    "SET standard_conforming_strings = on;",
    "SELECT pg_catalog.set_config('search_path', '', false);",
    '',
    'CREATE TABLE public.principal (',
    '    id uuid NOT NULL',
    ');',
    '',
    'CREATE FUNCTION public.fixture_fn() RETURNS void',
    '    LANGUAGE plpgsql',
    '    AS $_$',
    'BEGIN',
    "COPY principal TO stdout; RAISE NOTICE 'not; a statement';",
    'END',
    '$_$;',
    '',
  ];
  for (const [table, columns] of [...DUMP_TABLES].reverse()) {
    const { rows } = await client.query(
      `SELECT ${columns.map((column) => `${column}::text AS ${column}`).join(', ')} FROM ${table} ORDER BY 1`,
    );
    out.push(`COPY public.${table} (${columns.join(', ')}) FROM stdin;`);
    for (const row of rows) out.push(columns.map((column) => copyField(row[column])).join('\t'));
    out.push('\\.', '');
  }
  const { rows: [{ max }] } = await client.query('SELECT max(seq)::text AS max FROM evidence');
  out.push(`SELECT pg_catalog.setval('public.evidence_seq_seq', ${max}, true);`, '');
  out.push('ALTER TABLE ONLY public.principal', '    ADD CONSTRAINT principal_pkey PRIMARY KEY (id);', '');
  out.push('\\unrestrict fixtureRestrictKey0123456789', '');
  return out.join('\n');
}

/** Writes a dump and returns reconstruction options whose manifest pins it. */
async function optionsForDump(name, sql) {
  const bytes = gzipSync(sql);
  const path = join(tmp, name);
  await writeFile(path, bytes);
  const manifest = structuredClone(fixture.manifest);
  manifest.dump = { ...fixture.manifest.dump, path, sha256: sha256Hex(bytes), bytes: bytes.length };
  return baseOptions({ manifest, dumpPath: path });
}

async function assertRoundTrip(result) {
  assert.equal(result.ok, true, JSON.stringify(result.failures));
  assert.equal(result.stage, 'recovered');
  const expected = await readHistory(() => source.connect(), TENANT);
  const actual = await readHistory(() => result.target.connect(), TENANT);
  assert.deepEqual(JSON.parse(JSON.stringify(actual)), JSON.parse(JSON.stringify(expected)));
  await result.access.client.end();
}

test('a pg_dump-format dump (\\restrict, COPY blocks out of foreign-key order, colliding DDL) reconstructs the same history', async () => {
  const result = await reconstructRecovery(await optionsForDump('dump-pgdump.sql.gz', await renderPgDumpSql(sourceClient)));
  await assertRoundTrip(result);
});

test('a real pg_dump of the source reconstructs the same history', async (t) => {
  const url = process.env.KEEL_DB_TEST_URL;
  const dump = spawnSync('pg_dump', ['--schema', source.schema, url], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  if (dump.error || dump.status !== 0) {
    t.skip(`pg_dump unavailable for this server: ${dump.error?.message ?? dump.stderr.trim()}`);
    return;
  }
  // The source lives in an isolated test schema; production dumps name public.
  const sql = dump.stdout.replaceAll(`"${source.schema}"`, 'public').replaceAll(source.schema, 'public');
  assert.match(sql, /^COPY public\.evidence /m, 'the real dump carries COPY blocks');
  const result = await reconstructRecovery(await optionsForDump('dump-real.sql.gz', sql));
  await assertRoundTrip(result);
});

test('a dump carrying any psql meta-command other than \\restrict is refused at import', async () => {
  const sql = `${await renderPgDumpSql(sourceClient)}\n\\! touch /tmp/keel-should-not-run\n`;
  const result = await reconstructRecovery(await optionsForDump('dump-meta.sql.gz', sql));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'import');
  assert.ok(result.failures.some((f) => f.includes('meta-command \\!')), JSON.stringify(result.failures));
});

test('COPY text fields decode NULL, escapes, octal and hex bytes', () => {
  assert.equal(decodeCopyField('\\N'), null);
  assert.equal(decodeCopyField('plain'), 'plain');
  assert.equal(decodeCopyField('a\\tb\\nc\\\\d\\re'), 'a\tb\nc\\d\re');
  assert.equal(decodeCopyField('\\303\\251t\\xc3\\xa9'), 'été');
  assert.equal(decodeCopyField('\\\\x0a'), '\\x0a', 'a bytea literal survives');
  const items = parseDump("\\restrict k\nCOPY public.t (a, b) FROM stdin;\n1\t\\N\n\\.\nSELECT 'x;y';\n\\unrestrict k\n");
  assert.deepEqual(items.map((item) => item.kind), ['meta', 'copy', 'sql', 'meta']);
  assert.deepEqual(items[1].rows, ['1\t\\N']);
  assert.equal(items[2].text, "SELECT 'x;y'");
});

test('reconstructed schedule read is scoped to the requested tenant (multi-tenant fixture; mutation pin: remove tenant_ref filter from reconstructed schedule query)', async () => {
  const result = await reconstructRecovery(baseOptions());
  assert.equal(result.ok, true, JSON.stringify(result.failures));
  // Only the requested tenant's six schedules come back through the
  // recovered-history read...
  assert.equal(result.recovered.schedules.length, 6);
  assert.ok(result.recovered.schedules.every((row) => row.tenant_ref === TENANT));
  // ...even though the other tenant's six schedules were imported into the
  // very same disposable database from the very same dump. If the tenant_ref
  // filter were removed from the recovered-history query, this would be 12
  // and the assertion above would fail.
  const { rows } = await result.access.query(
    'SELECT count(*)::int AS n FROM schedule WHERE tenant_ref = $1',
    [OTHER_TENANT],
  );
  assert.equal(rows[0].n, 6, "the other tenant's schedules are present in the reconstructed database");
  await result.access.client.end();
});

test('reconstructRecovery refuses an invalid or missing tenantRef before any manifest check (mutation pin: remove top-level assertTenantRef guard in reconstructRecovery)', async () => {
  let created = 0;
  const spyTarget = async () => { created += 1; return newTarget(); };

  // An undefined tenantRef flows straight into verifyRecoveryManifest as
  // expectedTenantRef, where `expectedTenantRef !== undefined && …` SKIPS the
  // manifest's own tenant-pin check entirely — an unpinned reconstruction
  // against any tenant's manifest. The top-level assertTenantRef guard must
  // refuse this before the manifest is even read.
  await assert.rejects(
    reconstructRecovery(baseOptions({ tenantRef: undefined, createTargetDatabase: spyTarget })),
    /must be a derived tenant reference/,
  );
  assert.equal(created, 0, 'an undefined tenantRef must not reach manifest verification or import');

  // A raw (unhashed) tenant id is equally refused — only a derived
  // sha256:… reference may anchor a reconstruction.
  await assert.rejects(
    reconstructRecovery(baseOptions({ tenantRef: 'raw-tenant-id', createTargetDatabase: spyTarget })),
    /must be a derived tenant reference/,
  );
  assert.equal(created, 0);
});

test('tampered manifest or head is refused before any database is created (mutation pin)', async () => {
  let created = 0;
  const spyTarget = async () => { created += 1; return newTarget(); };

  // Forged dump checksum in the manifest.
  const forged = structuredClone(fixture.manifest);
  forged.dump.sha256 = '0'.repeat(64);
  let result = await reconstructRecovery(baseOptions({ manifest: forged, createTargetDatabase: spyTarget }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'manifest');
  assert.ok(result.failures.some((f) => f.includes('dump checksum mismatch')));
  assert.equal(created, 0, 'no disposable database on a tampered manifest');

  // A moved evidence head: the manifest checkpoint no longer matches the
  // verifier's current head.
  const moved = structuredClone(fixture.manifest);
  moved.evidenceCheckpoint = { headSeq: 99, headHash: '0'.repeat(64), recordCount: 99 };
  result = await reconstructRecovery(baseOptions({ manifest: moved, createTargetDatabase: spyTarget }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'manifest');
  assert.ok(result.failures.some((f) => f.includes('evidence checkpoint mismatch')));
  assert.equal(created, 0);

  // Tampered artifact bytes under an intact manifest.
  await appendFile(fixture.dumpPath, 'tampered');
  result = await reconstructRecovery(baseOptions({ createTargetDatabase: spyTarget }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'manifest');
  assert.ok(result.failures.some((f) => f.includes('dump checksum mismatch')));
  await writeFile(fixture.dumpPath, fixture.dumpBytes);
  assert.equal(created, 0);

  // A manifest whose checkpoint disagrees with the history the dump actually
  // carries is caught at the history stage when the verifier had no head to
  // check against up front (the task-67 "incomplete" gap becomes a refusal
  // here — reconstruction requires the head to match).
  const lying = structuredClone(fixture.manifest);
  lying.evidenceCheckpoint = {
    headSeq: fixture.checkpoint.headSeq,
    headHash: '0'.repeat(64),
    recordCount: fixture.checkpoint.recordCount,
  };
  result = await reconstructRecovery(baseOptions({
    manifest: lying,
    expectedCheckpoint: undefined,
    createTargetDatabase: newTarget,
  }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'history');
  assert.ok(result.failures.some((f) => f.includes('evidence head mismatch')));
  assert.deepEqual(result.incomplete, [INCOMPLETE_EVIDENCE_CHECKPOINT]);
  await result.access.client.end();
});

test('corrupted evidence history inside the dump is caught after import', async () => {
  const corruptBytes = gzipSync(await renderDumpSql(sourceClient, { corruptEvidenceHash: true }));
  const corruptPath = join(tmp, 'dump-corrupt.sql.gz');
  await writeFile(corruptPath, corruptBytes);
  // The manifest honestly checksums the corrupt dump: artifact verification
  // passes, but the reconstructed chain does not.
  const manifest = structuredClone(fixture.manifest);
  manifest.dump = Object.freeze({ ...fixture.manifest.dump, path: corruptPath, sha256: sha256Hex(corruptBytes), bytes: corruptBytes.length });

  const result = await reconstructRecovery(baseOptions({ manifest, dumpPath: corruptPath }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'history');
  assert.ok(result.failures.some((f) => f.includes('evidence chain verification failed')));
  await result.access.client.end();
});

test('anonymous or unauthenticated recovery identity is refused (mutation pin)', async () => {
  let created = 0;
  const spyTarget = async () => { created += 1; return newTarget(); };
  let authenticatorCalls = 0;
  const countingAuthenticator = async () => { authenticatorCalls += 1; return true; };

  // Anonymous emergency identity: refused before the authenticator is even
  // consulted. A mutator deleting the anonymous branch fails this test.
  let result = await reconstructRecovery(baseOptions({
    identity: { anonymous: true, principalId: 'emergency', credentialRef: 'break-glass' },
    authenticator: countingAuthenticator,
    createTargetDatabase: spyTarget,
  }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'identity');
  assert.ok(result.failures.some((f) => f.includes('anonymous recovery identity is refused')));
  assert.equal(authenticatorCalls, 0);
  assert.equal(created, 0);

  // Missing principal id is equally anonymous.
  result = await reconstructRecovery(baseOptions({
    identity: { credentialRef: 'break-glass' },
    authenticator: countingAuthenticator,
    createTargetDatabase: spyTarget,
  }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'identity');
  assert.equal(authenticatorCalls, 0);

  // No independent authenticator configured: this process cannot authenticate
  // anyone by itself.
  result = await reconstructRecovery(baseOptions({ authenticator: undefined, createTargetDatabase: spyTarget }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'identity');
  assert.ok(result.failures.some((f) => f.includes('independent authenticator')));

  // The independent channel refuses.
  result = await reconstructRecovery(baseOptions({ authenticator: async () => false, createTargetDatabase: spyTarget }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'identity');
  assert.ok(result.failures.some((f) => f.includes('refused recovery identity')));

  // A truthy-but-not-`true` decision (an object, a non-empty string, a
  // non-zero number) must be refused just like `false`. A mutator loosening
  // `decision !== true` to `!decision` would accept these and fails here.
  for (const nonTrueDecision of [{ ok: false }, 'false', 1, [], 'true']) {
    result = await reconstructRecovery(baseOptions({
      authenticator: async () => nonTrueDecision,
      createTargetDatabase: spyTarget,
    }));
    assert.equal(result.ok, false, `decision ${JSON.stringify(nonTrueDecision)} must be refused`);
    assert.equal(result.stage, 'identity');
    assert.ok(result.failures.some((f) => f.includes('refused recovery identity')));
  }

  // A credential reference that IS credential material is refused (GC#6).
  result = await reconstructRecovery(baseOptions({
    identity: { principalId: 'recovery-officer@example.test', credentialRef: 'password=hunter2' },
    authenticator: countingAuthenticator,
    createTargetDatabase: spyTarget,
  }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'identity');
  assert.equal(created, 0, 'identity refusals never reach the database');

  // The authenticator receives exactly the claimed identity.
  let seen = null;
  result = await reconstructRecovery(baseOptions({
    authenticator: async (claimed) => { seen = claimed; return true; },
  }));
  assert.equal(result.ok, true, JSON.stringify(result.failures));
  assert.deepEqual(seen, {
    principalId: 'recovery-officer@example.test',
    credentialRef: 'break-glass token reference: safe #7, held by security officer',
  });
  await result.access.client.end();

  // Unit-level pins on the authz module itself.
  await assert.rejects(
    authenticateRecoveryIdentity({ identity: { anonymous: true }, authenticator: async () => true }),
    RecoveryIdentityError,
  );
  await assert.rejects(
    authenticateRecoveryIdentity({ identity: null, authenticator: async () => true }),
    RecoveryIdentityError,
  );
  await assert.rejects(
    authenticateRecoveryIdentity({ identity: { principalId: 'p', credentialRef: 'c' } }),
    /independent authenticator/,
  );
  for (const nonTrueDecision of [{ ok: false }, 'false', 1, [], 'true']) {
    await assert.rejects(
      authenticateRecoveryIdentity({
        identity: { principalId: 'p', credentialRef: 'c' },
        authenticator: async () => nonTrueDecision,
      }),
      RecoveryIdentityError,
      `decision ${JSON.stringify(nonTrueDecision)} must be refused`,
    );
  }
  const token = await authenticateRecoveryIdentity({
    identity: { principalId: 'p', credentialRef: 'c' },
    authenticator: async () => true,
    at: new Date('2026-09-22T00:00:00.000Z'),
  });
  assert.equal(token.independent, true);
  assert.equal(token.authenticatedAt, '2026-09-22T00:00:00.000Z');
  assert.ok(Object.isFrozen(token));
});

test('missing credentials produce named prerequisites, in stable order', async () => {
  let created = 0;
  const spyTarget = async () => { created += 1; return newTarget(); };

  let result = await reconstructRecovery(baseOptions({ credentials: {}, createTargetDatabase: spyTarget }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'prerequisites');
  assert.deepEqual(result.prerequisites, [
    PREREQUISITE_RECOVERY_KEY_MATERIAL,
    PREREQUISITE_ARTIFACT_STORAGE_READ,
    PREREQUISITE_TENANT_RECOVERY_AUTHORIZATION,
  ]);
  assert.ok(result.failures.some((f) => f.includes(`missing credential prerequisite: ${PREREQUISITE_RECOVERY_KEY_MATERIAL}`)));
  assert.equal(created, 0, 'nothing is verified or imported while prerequisites are missing');

  // A partial set names exactly the remaining gaps.
  result = await reconstructRecovery(baseOptions({
    credentials: { recoveryKeyMaterial: 'sealed envelope #7, offline safe' },
    createTargetDatabase: spyTarget,
  }));
  assert.equal(result.ok, false);
  assert.deepEqual(result.prerequisites, [
    PREREQUISITE_ARTIFACT_STORAGE_READ,
    PREREQUISITE_TENANT_RECOVERY_AUTHORIZATION,
  ]);

  // A "reference" that embeds credential material does not satisfy the
  // prerequisite — it is named missing, and the material goes nowhere.
  result = await reconstructRecovery(baseOptions({
    credentials: {
      recoveryKeyMaterial: '-----BEGIN RSA PRIVATE KEY-----\nMII...',
      artifactStorageRead: 'backup service account reference',
      tenantRecoveryAuthorization: 'change record CR-2026-0915',
    },
    createTargetDatabase: spyTarget,
  }));
  assert.equal(result.ok, false);
  assert.deepEqual(result.prerequisites, [PREREQUISITE_RECOVERY_KEY_MATERIAL]);
  assert.equal(created, 0);

  // Unit-level: pure listing, stable order, empty when satisfied.
  assert.deepEqual(listMissingPrerequisites({}), [
    PREREQUISITE_RECOVERY_KEY_MATERIAL,
    PREREQUISITE_ARTIFACT_STORAGE_READ,
    PREREQUISITE_TENANT_RECOVERY_AUTHORIZATION,
  ]);
  assert.deepEqual(listMissingPrerequisites({
    credentials: {
      recoveryKeyMaterial: 'a', artifactStorageRead: 'b', tenantRecoveryAuthorization: 'c',
    },
  }), []);
});

test('incompatible schema stops before import', async () => {
  let created = 0;
  const spyTarget = async () => { created += 1; return newTarget(); };

  // The manifest pins a schema this build does not have: refused at manifest
  // verification (the task-67 schema pin check), before any import.
  const foreign = structuredClone(fixture.manifest);
  foreign.build = Object.freeze({ ...fixture.manifest.build, schemaPin: '0'.repeat(64) });
  let result = await reconstructRecovery(baseOptions({ manifest: foreign, createTargetDatabase: spyTarget }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'manifest');
  assert.ok(result.failures.some((f) => f.includes('schema pin mismatch')));
  assert.equal(created, 0);

  // Even if the caller's expectedBuild is bent to match the foreign pin (so
  // manifest verification passes), the schema ABOUT TO BE APPLIED is hashed
  // and compared — a mismatch stops before a database is created.
  result = await reconstructRecovery(baseOptions({
    manifest: foreign,
    expectedBuild: { revision: BUILD_REVISION, schemaPin: '0'.repeat(64) },
    createTargetDatabase: spyTarget,
  }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'schema');
  assert.ok(result.failures.some((f) => f.includes('refusing to import into an incompatible schema')));
  assert.equal(created, 0);

  // A non-gzip or garbage dump can never reach the import phase either.
  const garbagePath = join(tmp, 'dump-garbage.sql.gz');
  const garbage = Buffer.from('not gzip at all');
  await writeFile(garbagePath, garbage);
  const garbageManifest = structuredClone(fixture.manifest);
  garbageManifest.dump = Object.freeze({
    ...fixture.manifest.dump, path: garbagePath, sha256: sha256Hex(garbage), bytes: garbage.length,
  });
  result = await reconstructRecovery(baseOptions({
    manifest: garbageManifest, dumpPath: garbagePath, createTargetDatabase: spyTarget,
  }));
  assert.equal(result.ok, false);
  assert.equal(result.stage, 'import');
  assert.ok(result.failures.some((f) => f.includes('not gzip-compressed SQL')));
  assert.equal(created, 0);
});

test('read-only session guard: unit pins', async () => {
  const client = await source.connect();
  try {
    const access = await openRecoveryReadOnlySession(client);
    assert.equal(access.readOnly, true);
    // Reads pass.
    await access.query('SELECT 1');
    await access.query('WITH x AS (SELECT 1) SELECT * FROM x');
    await access.query("VALUES (1)");
    await access.query('TABLE evidence_head');
    await access.query('EXPLAIN SELECT 1');
    await access.query('SELECT updated_at, created_at FROM schedule');
    // Keywords the guard refuses are data inside string literals, dollar
    // quotes, quoted identifiers and comments — never false positives.
    await access.query("SELECT '-- DELETE FROM evidence; SET default_transaction_read_only = off' AS note");
    await access.query('SELECT $$update evidence set enabled = false$$ AS a, $tag$DELETE;$tag$ AS b');
    await access.query('SELECT 1 /* DELETE FROM evidence; SELECT 1 */');
    // Writes are refused by the guard and by the database.
    for (const sql of [
      // Direct writes.
      'INSERT INTO principal (email) VALUES (\'x\')',
      'UPDATE principal SET email = \'x\'',
      'DELETE FROM principal',
      'DROP TABLE principal',
      'TRUNCATE principal',
      // Writable CTEs and DML after a WITH clause — the leading WITH must
      // not smuggle them past the guard (KEEL-VERIFY: writable CTE).
      'WITH d AS (DELETE FROM evidence RETURNING *) SELECT * FROM d',
      'with u as (update schedule set enabled = false returning *) select * from u',
      'WITH i AS (INSERT INTO principal (email) VALUES (\'x\') RETURNING *) SELECT * FROM i',
      'WITH x AS (SELECT 1) DELETE FROM evidence',
      'WITH x AS (SELECT 1) UPDATE principal SET email = \'x\'',
      // Transaction-mode resets and multi-statement smuggling (KEEL-VERIFY:
      // resetting transaction mode).
      'SET default_transaction_read_only = off',
      'RESET ALL',
      'SELECT 1; SET default_transaction_read_only = off',
      'SELECT 1; DELETE FROM evidence',
      'SELECT 1;',
      "SELECT set_config('default_transaction_read_only', 'off', false)",
      // EXPLAIN ANALYZE executes the explained statement; SELECT INTO writes.
      'EXPLAIN ANALYZE DELETE FROM evidence',
      'EXPLAIN (ANALYZE) SELECT 1',
      'SELECT * INTO scratch FROM schedule',
      // Sequence state mutation.
      "SELECT nextval('evidence_seq_seq')",
      "SELECT setval('evidence_seq_seq', 1)",
    ]) {
      await assert.rejects(access.query(sql), RecoveryReadOnlyError, sql);
    }
    await assert.rejects(client.query("INSERT INTO principal (email) VALUES ('x')"), (e) => e.code === '25006');
    // The mode-reset attempts did not bend the session: it is still read-only.
    const { rows: [mode] } = await access.query('SHOW transaction_read_only');
    assert.equal(mode.transaction_read_only, 'on');
  } finally {
    await client.end();
  }
});

test('CLI: full reconstruction, refusal without authenticator, named prerequisites', async () => {
  const quiet = { errors: [], lines: [] };
  const logger = {
    log(line) { quiet.lines.push(String(line)); },
    error(line) { quiet.errors.push(String(line)); },
  };
  const cliArgs = () => [
    'node', 'reconstruct.mjs',
    '--manifest', fixture.manifestPath,
    '--dump', fixture.dumpPath,
    '--tenant-ref', TENANT,
    '--build-revision', BUILD_REVISION,
    '--schema-pin', schemaPin,
    '--config-export-dir', fixture.exportDir,
    '--evidence-head', `${fixture.checkpoint.headSeq}:${fixture.checkpoint.headHash}:${fixture.checkpoint.recordCount}`,
    '--target-url', 'postgres://unused-injected-target',
    '--identity-principal', 'recovery-officer@example.test',
    '--credential-ref', 'break-glass token reference: safe #7',
    '--recovery-key-ref', 'sealed envelope #7, offline safe',
    '--storage-read-ref', 'backup service account reference',
    '--tenant-authz-ref', 'change record CR-2026-0915',
  ];

  // Happy path: injected independent authenticator and disposable target.
  let exit = await runCli({
    argv: cliArgs(),
    logger,
    dependencies: { authenticator: async () => true, createTargetDatabase: newTarget },
  });
  assert.equal(exit, 0, JSON.stringify(quiet.errors));
  assert.ok(quiet.lines.some((line) => line.includes('recovered read-only as recovery-officer@example.test (writers disabled)')));
  assert.ok(quiet.lines.some((line) => line.includes('schedules: 6')));
  assert.ok(quiet.lines.some((line) => line.includes('approvals: 2')));
  assert.ok(quiet.lines.some((line) => line.includes('grants: 2')));

  // Without an independent authenticator the CLI refuses — there is no
  // anonymous path through the command line either.
  quiet.errors = []; quiet.lines = [];
  exit = await runCli({ argv: cliArgs(), logger, dependencies: { createTargetDatabase: newTarget } });
  assert.equal(exit, 1);
  assert.ok(quiet.errors.some((line) => line.includes('independent authenticator')));

  // Missing credential flags name the missing prerequisites.
  quiet.errors = []; quiet.lines = [];
  const withoutCredentials = cliArgs().filter((arg, i, argv) =>
    argv[i - 1] !== '--recovery-key-ref' && arg !== '--recovery-key-ref'
    && argv[i - 1] !== '--tenant-authz-ref' && arg !== '--tenant-authz-ref');
  exit = await runCli({
    argv: withoutCredentials,
    logger,
    dependencies: { authenticator: async () => true, createTargetDatabase: newTarget },
  });
  assert.equal(exit, 1);
  assert.ok(quiet.errors.some((line) => line.includes(`missing credential prerequisite: ${PREREQUISITE_RECOVERY_KEY_MATERIAL}`)));
  assert.ok(quiet.errors.some((line) => line.includes(`missing credential prerequisite: ${PREREQUISITE_TENANT_RECOVERY_AUTHORIZATION}`)));

  // A tampered manifest fails through the CLI with exit 1.
  const tamperedPath = join(tmp, 'recovery-tampered.json');
  const tampered = structuredClone(fixture.manifest);
  tampered.dump = Object.freeze({ ...tampered.dump, sha256: '0'.repeat(64) });
  await writeFile(tamperedPath, JSON.stringify(tampered));
  quiet.errors = []; quiet.lines = [];
  exit = await runCli({
    argv: cliArgs().flatMap((arg, i, argv) => (argv[i - 1] === '--manifest' ? [tamperedPath] : [arg])),
    logger,
    dependencies: { authenticator: async () => true, createTargetDatabase: newTarget },
  });
  assert.equal(exit, 1);
  assert.ok(quiet.errors.some((line) => line.includes('dump checksum mismatch')));

  exit = await runCli({ argv: ['node', 'reconstruct.mjs', '--help'], logger });
  assert.equal(exit, 0);
  assert.ok(quiet.lines.some((line) => line.includes('--manifest')));
});

test('CLI imports the verified --dump override rather than the manifest path', async () => {
  // Both dumps carry a valid evidence chain, but different schedules. Merely
  // checking the chain would let an import of the unverified original pass.
  const relocatedBytes = gzipSync(await renderDumpSql(sourceClient, { omitTables: ['schedule'] }));
  const relocatedPath = join(tmp, 'relocated.sql.gz');
  await writeFile(relocatedPath, relocatedBytes);
  const manifest = structuredClone(fixture.manifest);
  manifest.dump.sha256 = sha256Hex(relocatedBytes);
  manifest.dump.bytes = relocatedBytes.length;
  // Keep manifest.dump.path pointing to the original six-schedule dump.
  const manifestPath = join(tmp, 'relocated-recovery.json');
  await writeFile(manifestPath, JSON.stringify(manifest));
  const lines = [];
  const errors = [];
  let created = 0;
  const argv = [
    'node', 'reconstruct.mjs',
    '--manifest', manifestPath,
    '--dump', relocatedPath,
    '--tenant-ref', TENANT,
    '--build-revision', BUILD_REVISION,
    '--schema-pin', schemaPin,
    '--config-export-dir', fixture.exportDir,
    '--evidence-head', `${fixture.checkpoint.headSeq}:${fixture.checkpoint.headHash}:${fixture.checkpoint.recordCount}`,
    '--identity-principal', 'recovery-officer@example.test',
    '--credential-ref', 'offline identity reference',
    '--recovery-key-ref', 'offline key reference',
    '--storage-read-ref', 'artifact reader reference',
    '--tenant-authz-ref', 'recovery authorization reference',
  ];
  const options = {
    argv,
    logger: { log: (line) => lines.push(line), error: (line) => errors.push(line) },
    dependencies: {
      authenticator: async () => true,
      createTargetDatabase: async () => { created += 1; return newTarget(); },
    },
  };
  assert.equal(await runCli(options), 0, JSON.stringify(errors));
  assert.equal(created, 1);
  assert.ok(lines.includes('schedules: 0'), JSON.stringify(lines));
  assert.ok(lines.includes('approvals: 2'));
  assert.ok(lines.includes('grants: 2'));

  // A corrupt override must be refused even when the manifest path holds a
  // valid dump: verification must honor the override as well as import.
  await appendFile(relocatedPath, 'tampered');
  argv[argv.indexOf('--manifest') + 1] = fixture.manifestPath;
  errors.length = 0;
  assert.equal(await runCli(options), 1);
  assert.ok(errors.some((line) => line.includes('dump checksum mismatch')));
  assert.equal(created, 1, 'a corrupt override must not create a target');

  // Omitting the override still imports the artifact named by the manifest.
  const result = await reconstructRecovery(baseOptions({ dumpPath: undefined }));
  try {
    assert.equal(result.ok, true, JSON.stringify(result.failures));
    assert.equal(result.recovered.schedules.length, 6);
  } finally {
    await result.access?.client.end();
  }
});

test('the default disposable target factory refuses the production database URL', async () => {
  const production = 'postgres://keel@db/keel';
  await assert.rejects(
    createDisposableTarget({ targetUrl: production, dependencies: { env: { KEEL_DB_URL: production } } }),
    /refusing to reconstruct into the production database URL/,
  );
  await assert.rejects(createDisposableTarget({ targetUrl: '' }), TypeError);
});

test('CLI with the production signed-assertion authenticator recovers and writes the gate reconstruction.json', async () => {
  // The trust root and replay ledger live outside the backup set (tmp holds
  // the manifest, dump and export).
  const trustRoot = mkdtempSync(join(tmpdir(), 'keel-recovery-trust-'));
  try {
    const officer = generateKeyPairSync('ed25519');
    const trustStorePath = join(trustRoot, 'recovery-authenticators.json');
    await writeFile(trustStorePath, JSON.stringify({
      version: 1,
      principals: [{ principalId: 'recovery-officer@example.test', keyId: 'officer-1', publicKey: officer.publicKey.export({ type: 'spki', format: 'pem' }) }],
    }), { mode: 0o644 });
    const assertionPath = join(trustRoot, 'assertion.json');
    await writeFile(assertionPath, JSON.stringify(signRecoveryAssertion({
      privateKey: officer.privateKey, principalId: 'recovery-officer@example.test', keyId: 'officer-1', tenantRef: TENANT,
    })));
    const resultOut = join(trustRoot, 'reconstruction.json');
    const lines = [];
    const errors = [];
    const argv = [
      'node', 'reconstruct.mjs',
      '--manifest', fixture.manifestPath,
      '--dump', fixture.dumpPath,
      '--tenant-ref', TENANT,
      '--build-revision', BUILD_REVISION,
      '--schema-pin', schemaPin,
      '--config-export-dir', fixture.exportDir,
      '--evidence-head', `${fixture.checkpoint.headSeq}:${fixture.checkpoint.headHash}:${fixture.checkpoint.recordCount}`,
      '--identity-principal', 'recovery-officer@example.test',
      '--credential-ref', assertionPath,
      '--authenticator', 'signed-assertion',
      '--recovery-trust-store', trustStorePath,
      '--recovery-replay-ledger', join(trustRoot, 'replay'),
      '--recovery-key-ref', 'sealed envelope #7, offline safe',
      '--storage-read-ref', 'backup service account reference',
      '--tenant-authz-ref', 'change record CR-2026-1004',
      '--result-out', resultOut,
    ];
    const run = () => runCli({
      argv,
      logger: { log: (line) => lines.push(String(line)), error: (line) => errors.push(String(line)) },
      dependencies: { createTargetDatabase: newTarget },
    });
    assert.equal(await run(), 0, JSON.stringify(errors));
    assert.ok(lines.includes('recovered read-only as recovery-officer@example.test (writers disabled)'));

    const record = JSON.parse(await readFile(resultOut, 'utf8'));
    // Exactly the fields capture-drill reads, bound to tenant and build.
    assert.equal(record.ok, true);
    assert.equal(record.stage, 'recovered');
    assert.equal(record.readOnly, true);
    assert.equal(record.writersDisabled, true);
    assert.equal(record.tenantRef, TENANT);
    assert.equal(record.buildRevision, BUILD_REVISION);
    assert.ok(!Number.isNaN(Date.parse(record.completedAt)));
    assert.deepEqual(record.recovered.evidence, { chainOk: true, ...fixture.checkpoint });
    assert.equal(record.recovered.counts.schedules, 6);
    assert.equal(record.identity.authenticator, 'signed-assertion');
    assert.equal(record.identity.credentialRef, assertionPath);
    assert.equal(record.access, undefined, 'the access handle is never persisted');
    assert.equal(JSON.stringify(record).includes('requester@example.test'), false, 'no row contents');

    // The same assertion cannot authorize a second reconstruction.
    errors.length = 0;
    assert.equal(await run(), 1);
    assert.ok(errors.some((line) => line.startsWith('identity:') && line.includes('already used')), JSON.stringify(errors));
  } finally {
    rmSync(trustRoot, { recursive: true, force: true });
  }
});
